import './globals.css'
import Head from 'next/head';

export const metadata = {
  title: 'TraceX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.typekit.net/iwm0vai.css" />
      </Head>
      <body>{children}</body>
    </html>
  )
}
