name: Deploy Docker image

on:
  push:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: pnpm install

      - name: Run lint checks
        run: pnpm run lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set date and time variables
        id: datetime
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Build and push Docker image
        run: |
          docker build -t tracex/time:${{ steps.datetime.outputs.date }} .
          docker tag tracex/time:${{ steps.datetime.outputs.date }} ${{ secrets.DOCKER_USERNAME }}/tracex:${{ steps.datetime.outputs.date }}
          docker push ${{ secrets.DOCKER_USERNAME }}/tracex:${{ steps.datetime.outputs.date }}

      - name: SSH into the server and execute command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tracex:${{ steps.datetime.outputs.date }}
            docker run -d --name tracex -p 3501:3000 ${{ secrets.DOCKER_USERNAME }}/tracex:${{ steps.datetime.outputs.date }}
